// voting/src/app/booth.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core'

@Component({
    selector: 'booth',
    template: `
      <button
        class="m5"      
        *ngFor="let option of options; index as i"
        (click)="select.emit(i)"
      >
        {{ option }}
      </button>
    `,
    styles: [
      `
        .selected {
          font-weight: bold;
        }
      `
    ]
  })
  export class BoothComponent {
    @Input() options: string[] | undefined
    @Output() select = new EventEmitter<number>()

  }

// voting/src/components/Booth.vue
<template>
  <div>
    <button
      v-for="(option, index) in options"
      class="m5"
      :key="option"
      @click="$emit('select', index)"
    >
      {{ option }}
    </button>
  </div>
</template>

<script>
export default {
  name: "Booth",
  props: ["options"],
};
</script>

<style>
.selected {
  font-weight: bold;
}
</style>
