// voting/src/app/voting-card.component.ts
import { Component, Input } from '@angular/core';
@Component({
  selector: 'voting-card',
  template: `
    <div *ngIf="state === 'open'; else close">
      <div class="panel question">
        <p class="m5">{{ title }}</p>
        <booth [options]="options" (select)="select($event)"> </booth>
      </div>
      <button (click)="endVotation()" class="submitBtn">
        Encerrar votacao
      </button>
    </div>
    <ng-template #close>
      <div class="panel results">
        <result [votes]="votes"></result>
      </div>
    </ng-template>
  `,
  styles: [
    `
      .panel {
        padding: 10px;
        border-radius: 5px;
        border: 1px solid #ddd;
      }
      .question {
        background-color: azure;
      }
      .results {
        background-color: beige;
      }
      .submitBtn {
        margin: 15px;
      }
    `,
  ],
})
export class VotingCardComponent {
  state = 'open';
  @Input() title: string | undefined;
  @Input() votes!: Array<{ option: string; count: number }>;

  endVotation() {
    this.state = 'close';
  }

  select(index: any) {
    this.votes[index].count++;
  }

  public get options(): string[] {
    return this.votes.map((vote) => vote.option);
  }
}

// voting/src/components/VotingCard.vue
<template>
  <div>
    <div v-if="state === 'open'">
      <div class="panel question">
        <p class="m5">{{ title }}</p>
        <Booth :options="options" @select="select" />
      </div>
      <button v-on:click="endVotation" class="submitBtn">
        Encerrar votacao
      </button>
    </div>
    <div v-else>
      <div class="panel results">
        <Result :votes="votes" />
      </div>
    </div>
  </div>
</template>

<script>
import Booth from "./Booth";
import Result from "./Result";

let options = [];

export default {
  components: { Booth, Result },
  props: ['title', 'votes', 'state'],
  methods: {
    endVotation() {
      this.state = "close";
    },

    select(index) {
      this.votes[index].count++;
    },
  },
  computed: {
    options() {
      options = this.votes.map((vote) => vote.option);
      return options;
    },
  },
};
</script>


<style>
.panel {
  padding: 10px;
  border-radius: 5px;
  border: 1px solid #ddd;
}
.question {
  background-color: azure;
}
.results {
  background-color: beige;
}
.m5 {
  margin: 5px;
}
.submitBtn {
  margin: 15px;
}
</style>
