// voting/src/VotingList.svelte
<script>
  import { votingList, createVotingList } from "./voting.js";
  import VotingForm from "./VotingForm.svelte";
  import VotingCard from "./VotingCard.svelte";

  let mode = "view";
  let current = null;
  let votes = [];
  let title = '';

  let vtList = createVotingList();

  function addVoting() {
    mode = "form";
    vtList.create();
    current = $vtList.length - 1;
  }

  function editVoting(index) {
    current = index;
    mode = "form";
  }

  function removeVoting(index) {
    vtList.remove(index);
  }

  function updateChanges({ detail }) {
    vtList.change(detail, current);
    mode = "view";
  }

  function cancelChanges() {
    if (mode === "form") {
      removeVoting($vtList.length - 1);
    }
    mode = "view";
  }

  function chooseVoting(index) {
    votes = [];
    mode = "voting";
    title = $vtList[index].statement;
    $vtList[index].options.map((item) => {
      votes.push({ option: item, count: 0 });
    });
  }

  function home() {
    mode = "view";
  }
</script>

{#if mode === "view"}
  <h2>Votações</h2>
  <button on:click={addVoting}>Nova votação</button>
  {#each $vtList as voting, index}
    <p>
      <b>P: </b>
      {voting.statement}
      <button on:click={(e) => editVoting(index)}>Edita</button>
      <button on:click={(e) => removeVoting(index)}>Remove</button>
      <br />
      <b>R: </b>
      {#each voting.options as o, i}
        <span>
          {o}
          {#if i < voting.options.length - 1}
            <span>/ </span>
          {/if}
        </span>
      {/each}
      <button on:click={(e) => chooseVoting(index)}>Votar</button>
    </p>
  {/each}
{:else if mode === "form"}
  <VotingForm
    voting={$vtList[current]}
    on:update={updateChanges}
    on:cancel={cancelChanges}
  />
{:else if mode === "voting"}
  <h2>Votações</h2>
  <VotingCard {votes} {title} state="open" />
  <button on:click={(e) => home()}>Voltar para a tela de votações</button>
{/if}

// voting/src/components/VotingList.vue
<template>
  <div v-if="mode === 'view'">
    <h2>Votações</h2>
    <button @click="addVoting">Nova votação</button>
    <p v-for="(voting, i) in votings" :key="i">
      <b>P: </b> {{ voting.statement }}
      <button className="m5" @click="editVoting(i)">Edita</button>
      <button className="m5" @click="removeVoting(i)">Remove</button>
      <br />
      <b>R: </b>
      <span v-for="(o, i) in voting.options" :key="i">
        {{ o }}
        <span v-if="i < voting.options.length - 1">/ </span>
      </span>
      <button className="m5" @click="chooseVoting(i)">Votar</button>
    </p>
  </div>
  <div v-else-if="mode === 'form'">
    <VotingForm
      :vote="votings[current]"
      @update="updateChanges"
      @cancel="cancelChanges"
    />
  </div>
  <div v-else>
    <voting-card
      :title="title"
      :options="votingOptions"
      @update="updateState"
    />
    <button className="m5" @click="home()">Voltar para tela de votações</button>
  </div>
</template>

<script>
import VotingForm from "./VotingForm";
import VotingCard from "./VotingCard.vue";
import { ref } from "vue";

import {
  votings,
  size,
  createVoting,
  updateVoting,
  deleteVoting,
} from "./voting";

// let state = 'open';

export default {
  components: { VotingForm, VotingCard },
//   data() {
//     return {
//       state: "open",
//     };
//   },
  setup() {
    const mode = ref("view");
    const current = ref(0);
    const title = ref("");
    const votingOptions = ref([]);
    // const stateView = ref("open");

    const addVoting = () => {
      createVoting();
      mode.value = "form";
      current.value = size.value - 1;
    };

    const updateChanges = (vote) => {
      updateVoting(vote, current.value);
      mode.value = "view";
    };

    const editVoting = (index) => {
      current.value = index;
      mode.value = "form";
    };

    const removeVoting = (index) => {
      deleteVoting(index);
    };

    const cancelChanges = () => {
      if (mode.value === "form") {
        deleteVoting(size.value - 1);
      }
      mode.value = "view";
    };

    const chooseVoting = (index) => {
      votingOptions.value = [];
      mode.value = "voting";
      title.value = votings[index].statement;
      votings[index].options.map((item) => {
        votingOptions.value.push({ option: item, count: 0 });
      });
    };

    const home = () => {
      mode.value = "view";
    };

    const updateState = () => {
      console.log("a");
    };

    return {
      mode,
      votings,
      current,
      addVoting,
      updateChanges,
      editVoting,
      removeVoting,
      cancelChanges,
      title,
      votingOptions,
      chooseVoting,
      home,
    //   stateView,
      updateState,
    };
  },
};
</script>
